name: Build PDFs

on:
  push:
    branches: ['**']
  pull_request:

jobs:

  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: pandoc/latex:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache bash findutils python3

      - name: List files (debug)
        run: ls -la

      - name: Generate PDFs
        run: python3 scripts/pdf/convert_md_to_pdf.py

      - name: Package PDFs as tar.gz
        if: always()
        run: |
          set -euo pipefail
          mkdir -p dist
          if find . -type f -name '*.pdf' | grep -q .; then
            tar -czf dist/pdfs-bundle.tar.gz $(find . -type f -name '*.pdf' -print)
          else
            # create an empty archive to keep workflow predictable
            tar -czf dist/pdfs-bundle.tar.gz -T /dev/null
          fi
          ls -la dist

      - name: Upload PDF bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: interview-prep-pdfs-bundle
          path: dist/pdfs-bundle.tar.gz
          if-no-files-found: warn
          retention-days: 30

      - name: Upload individual PDFs (optional)
        uses: actions/upload-artifact@v4
        with:
          name: interview-prep-pdfs-files
          path: "**/*.pdf"
          if-no-files-found: warn
          retention-days: 7

      - name: Publish 'latest' release asset
        if: always()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: PDFs Latest
          files: dist/pdfs-bundle.tar.gz
          body: |
            Auto-generated PDFs for the latest commit.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}