name: Build PDFs

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache bash findutils python3

      - name: List files (debug)
        run: ls -la

      - name: Generate PDFs
        run: python3 scripts/convert_md_to_pdf.py

      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v4
        with:
          name: interview-prep-pdfs
          path: "**/*.pdf"
          if-no-files-found: warn
          retention-days: 30